server:
  port: 8080

spring:
  application:
    name: dcloud-aipan
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.120.34.161:3306/dcloud_aipan?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: d6905295
    #redis配置
  data:
    redis:
      host: 47.120.34.161
      port: 6379
      password: d6905295
# mybatis-plus配置
mybatis-plus:
  global-config:
    #逻辑删除配置
    db-config:
      logic-delete-field: del # 全局逻辑删除的实体字段名
      logic-delete-value: 1 # 逻辑已删除值（默认为 1）
      logic-not-delete-value: 0 # 逻辑未删除值（默认为 0）
  configuration:
    # 日志输出配置
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true # 开启驼峰命名转换

# minio配置
minio:
  endpoint: http://47.120.34.161:9000
  access-key: admin
  access-secret: d6905295
  bucket-name: ai-pan
  avatar-bucket-name: avatar

ai:
  key: sk-0e4bacdd63ef4bffbcd5492f37eb38e5
